version: '2'

services:
  web:
    image: "nginx:1.11-alpine"
    ports:
        - "8000:80"
    volumes:
      - ./:/yona-cms
      - ./docker/log:/var/log/nginx
      - ./docker/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/conf/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php7
    networks:
      app_net:
        ipv4_address: 172.10.0.3

  php7:
    build: ./docker/php7/
    volumes:
      - ./:/yona-cms
      - ./docker/conf/www.conf:/etc/php/7.0/fpm/pool.d/www.conf
    environment:
      - TERM=xterm
      - APPLICATION_ENV=development
      - PHINX_ENVIRONMENT=development
    links:
      - mysql
    networks:
      app_net:
        ipv4_address: 172.10.0.4

  mysql:
    image: "mariadb:10.1.21"
    environment:
      - MYSQL_ROOT_PASSWORD=111
      - MYSQL_DATABASE=yona-cms
      - MYSQL_USER=root
      - MYSQL_PASSWORD=111
    volumes:
      - ./docker/data/mysql-data:/var/lib/mysql
      - ./:/yona-cms
    ports:
      - "3306:3306"
    networks:
      app_net:
        ipv4_address: 172.10.0.5

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.10.0.0/24
          gateway: 172.10.0.1